# Generated by Django 5.0 on 2024-02-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currencey',
            new_name='currency',
        ),
    ]
