# Generated by Django 5.0 on 2024-02-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'UZS'), (1, 'USD'), (2, 'RUB')]),
        ),
        migrations.CreateModel(
            name='ProductInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=150)),
                ('added_quantity', models.IntegerField()),
                ('added_time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stockregion')),
            ],
        ),
    ]
